# Generated by Django 5.2.16 on 2026-07-24 14:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_userprofile_profile_photo'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='role',
            field=models.CharField(choices=[('Candidate', 'Candidate'), ('HR', 'HR')], default='Candidate', max_length=20),
        ),
    ]
