# Generated by Django 5.2.16 on 2026-07-23 10:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobapplication',
            name='status',
            field=models.CharField(choices=[('Applied', 'Applied'), ('Interview Scheduled', 'Interview Scheduled'), ('Selected', 'Selected'), ('Rejected', 'Rejected')], default='Applied', max_length=30),
        ),
    ]
