# Generated by Django 5.2.16 on 2026-07-25 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0004_alter_jobapplication_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='interview_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobapplication',
            name='interview_time',
            field=models.TimeField(blank=True, null=True),
        ),
    ]
