# Generated by Django 5.2.16 on 2026-07-25 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0005_jobapplication_interview_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='offer_letter',
            field=models.FileField(blank=True, null=True, upload_to='offer_letters/'),
        ),
    ]
