# Generated by Django 5.2.16 on 2026-07-27 13:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0006_jobapplication_offer_letter'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobapplication',
            name='notification_read',
            field=models.BooleanField(default=False),
        ),
    ]
